Fixes #1108: Temporary Fix for Deprecated Qt functions
DistroAV/DistroAV pull request #1109
Opened 2024-10-15 21:19 UTC by LetsGOLowLevel

2024-10-17 23:18 UTC, paulpv commented
@AniketBose369 Please resolve the conflicts.
Why do you call these fixes "Temporary"?
Just remove the old code you commented out.

2024-10-17 23:19 UTC, paulpv commented on src/forms/obsndi-update.cpp
> +		//utcDateTime.setTimeSpec(Qt::UTC); fix it in issue-1108
remove this commented out line

2024-10-17 23:19 UTC, paulpv commented on src/forms/obsndi-update.cpp
> +			//&QCheckBox::stateChanged, fix it in issue-1108
remove this commented out line

2024-10-17 23:20 UTC, paulpv commented on src/forms/obsndi-update.cpp
> +#include <QTimeZone>
group with above #includes sorted alphabetically

2024-10-18 04:03 UTC, AniketBose369 commented
Ok

On Fri, 18 Oct, 2024, 4:50 am Paul Peavyhouse, ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In src/forms/obsndi-update.cpp
> <https://github.com/DistroAV/DistroAV/pull/1109#discussion_r1805581824>:
>
> > @@ -49,6 +49,8 @@ Inspiration(s):
>  #include <QTimer>
>  #include <QUrlQuery>
>
> +#include <QTimeZone>
>
> group with above #includes sorted alphabetically
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DistroAV/DistroAV/pull/1109#pullrequestreview-2376531058>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A57UWZCDYUADN54BIXYDYHTZ4BA4PAVCNFSM6AAAAABQABJW3GVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGNZWGUZTCMBVHA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-18 05:27 UTC, AniketBose369 commented
Done

2024-10-18 19:47 UTC, paulpv commented
@AniketBose369 Please fix the conflicts
![image](https://github.com/user-attachments/assets/558977c8-343f-4951-bb05-c227ca79ae8d)

2024-10-19 20:49 UTC, paulpv requested changes

2024-10-19 20:49 UTC, paulpv commented on src/forms/update.cpp
> +<<<<<<< HEAD:src/forms/obsndi-update.cpp
This is not how to resolve a code conflict

2024-10-22 15:33 UTC, BitRate27 commented
It seems obs-studio reverted the move of Qt to 6.7 on Sep 12 ( https://github.com/obsproject/obs-deps/commit/a0d86669aeb254a8778df535df0a9767ada30625 ) and went back to 6.6.3. This means the new checkStateChanged signal is not in the Qt from obs-studio rn.

2024-10-22 16:14 UTC, AniketBose369 commented
Actually I compiled and run DistroAV(basically linked the libndi.so.6 with
5) with the changes I made and the latest obs ran fine.

On Tue, Oct 22, 2024, 9:04 PM BitRate27 ***@***.***> wrote:

> It seems obs-studio reverted the move of Qt to 6.7 on Sep 12 (
> ***@***.***
> <https://github.com/obsproject/obs-deps/commit/a0d86669aeb254a8778df535df0a9767ada30625>
> ) and went back to 6.6.3. This means the new checkStateChanged signal is
> not in the Qt from obs-studio rn.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DistroAV/DistroAV/pull/1109#issuecomment-2429612529>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A57UWZATXFNSYAVSC74LOWDZ4ZV7JAVCNFSM6AAAAABQABJW3GVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMRZGYYTENJSHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-10-22 21:13 UTC, BitRate27 commented
Not exactly sure why that worked, but until they move to 6.7, we have to hold off as we won't be able to build. Since they reverted back, there must have been a major issue with 6.7, so we should wait until obs-studio settles on a new version. We can even look at this in Qt 6.8 as this one API isn't removed until 6.9.

2024-10-27 18:51 UTC, paulpv commented
@AniketBose369 @BitRate27 Shall we close this for now?
Once OBS officially supports Qt 6.7/8 we will update ours and this warning error should be obvious and then fixed.

2024-10-27 18:52 UTC, AniketBose369 commented
Yeah that seems the right choice

2024-10-27 20:57 UTC, closed without merging

2024-10-27 22:43 UTC, Trouffman commented
PR closed as this is "too early".

Revise / re-submit PR when : 
* OBS integrate QT 6.7+

To-do :
*  Update minimum required OBS version for DistroAV to support the new minimum requirement.

2025-08-29 13:23 UTC, Trouffman commented
@AniketBose369 a fix for you need has been merged to master. see #1151